export const languages = {
	"aa": {code: "aa", name: "Afar", nativeName: "Afaraf"},
	"ab": {code: "ab", name: "Abkhaz", nativeName: "Аҧсуа бызшәа"},
	"ae": {code: "ae", name: "Avestan", nativeName: "Avesta"},
	"af": {code: "af", name: "Afrikaans", nativeName: "Afrikaans"},
	"ak": {code: "ak", name: "Akan", nativeName: "Akan"},
	"am": {code: "am", name: "Amharic", nativeName: "አማርኛ"},
	"an": {code: "an", name: "Aragonese", nativeName: "Aragonés"},
	"ar": {code: "ar", name: "Arabic", nativeName: "اللغة العربية"},
	"as": {code: "as", name: "Assamese", nativeName: "অসমীয়া"},
	"av": {code: "av", name: "Avaric", nativeName: "Авар мацӀ"},
	"ay": {code: "ay", name: "Aymara", nativeName: "Aymar aru"},
	"az": {code: "az", name: "Azerbaijani", nativeName: "Azərbaycan dili"},
	"ba": {code: "ba", name: "Bashkir", nativeName: "Башҡорт теле"},
	"be": {code: "be", name: "Belarusian", nativeName: "Беларуская мова"},
	"bg": {code: "bg", name: "Bulgarian", nativeName: "Български език"},
	"bh": {code: "bh", name: "Bihari", nativeName: "भोजपुरी"},
	"bi": {code: "bi", name: "Bislama", nativeName: "Bislama"},
	"bm": {code: "bm", name: "Bambara", nativeName: "Bamanankan"},
	"bn": {code: "bn", name: "Bengali", nativeName: "বাংলা"},
	"bo": {code: "bo", name: "Tibetan Standard", nativeName: "བོད་ཡིག"},
	"br": {code: "br", name: "Breton", nativeName: "Brezhoneg"},
	"bs": {code: "bs", name: "Bosnian", nativeName: "Bosanski jezik"},
	"ca": {code: "ca", name: "Catalan", nativeName: "Català"},
	"ce": {code: "ce", name: "Chechen", nativeName: "Нохчийн мотт"},
	"ch": {code: "ch", name: "Chamorro", nativeName: "Chamoru"},
	"co": {code: "co", name: "Corsican", nativeName: "Corsu"},
	"cr": {code: "cr", name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ"},
	"cs": {code: "cs", name: "Czech", nativeName: "Čeština"},
	"cu": {code: "cu", name: "Old Church Slavonic", nativeName: "Ѩзыкъ словѣньскъ"},
	"cv": {code: "cv", name: "Chuvash", nativeName: "Чӑваш чӗлхи"},
	"cy": {code: "cy", name: "Welsh", nativeName: "Cymraeg"},
	"da": {code: "da", name: "Danish", nativeName: "Dansk"},
	"de": {code: "de", name: "German", nativeName: "Deutsch"},
	"dv": {code: "dv", name: "Divehi", nativeName: "Dhivehi"},
	"dz": {code: "dz", name: "Dzongkha", nativeName: "རྫོང་ཁ"},
	"ee": {code: "ee", name: "Ewe", nativeName: "Eʋegbe"},
	"el": {code: "el", name: "Greek", nativeName: "Ελληνικά"},
	"en": {code: "en", name: "English", nativeName: "English"},
	"eo": {code: "eo", name: "Esperanto", nativeName: "Esperanto"},
	"es": {code: "es", name: "Spanish", nativeName: "Español"},
	"et": {code: "et", name: "Estonian", nativeName: "Eesti"},
	"eu": {code: "eu", name: "Basque", nativeName: "Euskara"},
	"fa": {code: "fa", name: "Persian", nativeName: "فارسی"},
	"ff": {code: "ff", name: "Fula", nativeName: "Fulfulde"},
	"fi": {code: "fi", name: "Finnish", nativeName: "Suomi"},
	"fj": {code: "fj", name: "Fijian", nativeName: "Vakaviti"},
	"fo": {code: "fo", name: "Faroese", nativeName: "Føroyskt"},
	"fr": {code: "fr", name: "French", nativeName: "Français"},
	"fy": {code: "fy", name: "Western Frisian", nativeName: "Frysk"},
	"ga": {code: "ga", name: "Irish", nativeName: "Gaeilge"},
	"gd": {code: "gd", name: "Scottish Gaelic", nativeName: "Gàidhlig"},
	"gl": {code: "gl", name: "Galician", nativeName: "Galego"},
	"gn": {code: "gn", name: "Guaraní", nativeName: "Avañeẽ"},
	"gu": {code: "gu", name: "Gujarati", nativeName: "ગુજરાતી"},
	"gv": {code: "gv", name: "Manx", nativeName: "Gaelg"},
	"ha": {code: "ha", name: "Hausa", nativeName: "هَوُسَ"},
	"he": {code: "he", name: "Hebrew", nativeName: "עברית"},
	"hi": {code: "hi", name: "Hindi", nativeName: "हिन्दी"},
	"ho": {code: "ho", name: "Hiri Motu", nativeName: "Hiri Motu"},
	"hr": {code: "hr", name: "Croatian", nativeName: "Hrvatski jezik"},
	"ht": {code: "ht", name: "Haitian", nativeName: "Kreyòl ayisyen"},
	"hu": {code: "hu", name: "Hungarian", nativeName: "Magyar"},
	"hy": {code: "hy", name: "Armenian", nativeName: "Հայերեն"},
	"hz": {code: "hz", name: "Herero", nativeName: "Otjiherero"},
	"ia": {code: "ia", name: "Interlingua", nativeName: "Interlingua"},
	"id": {code: "id", name: "Indonesian", nativeName: "Indonesian"},
	"ie": {code: "ie", name: "Interlingue", nativeName: "Interlingue"},
	"ig": {code: "ig", name: "Igbo", nativeName: "Asụsụ Igbo"},
	"ii": {code: "ii", name: "Nuosu", nativeName: "ꆈꌠ꒿ Nuosuhxop"},
	"ik": {code: "ik", name: "Inupiaq", nativeName: "Iñupiaq"},
	"io": {code: "io", name: "Ido", nativeName: "Ido"},
	"is": {code: "is", name: "Icelandic", nativeName: "Íslenska"},
	"it": {code: "it", name: "Italian", nativeName: "Italiano"},
	"iu": {code: "iu", name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ"},
	"ja": {code: "ja", name: "Japanese", nativeName: "日本語"},
	"jv": {code: "jv", name: "Javanese", nativeName: "Basa Jawa"},
	"ka": {code: "ka", name: "Georgian", nativeName: "Ქართული"},
	"kg": {code: "kg", name: "Kongo", nativeName: "Kikongo"},
	"ki": {code: "ki", name: "Kikuyu", nativeName: "Gĩkũyũ"},
	"kj": {code: "kj", name: "Kwanyama", nativeName: "Kuanyama"},
	"kk": {code: "kk", name: "Kazakh", nativeName: "Қазақ тілі"},
	"kl": {code: "kl", name: "Kalaallisut", nativeName: "Kalaallisut"},
	"km": {code: "km", name: "Khmer", nativeName: "ខេមរភាសា"},
	"kn": {code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ"},
	"ko": {code: "ko", name: "Korean", nativeName: "한국어"},
	"kr": {code: "kr", name: "Kanuri", nativeName: "Kanuri"},
	"ks": {code: "ks", name: "Kashmiri", nativeName: "कश्मीरी"},
	"ku": {code: "ku", name: "Kurdish", nativeName: "Kurdî"},
	"kv": {code: "kv", name: "Komi", nativeName: "Коми кыв"},
	"kw": {code: "kw", name: "Cornish", nativeName: "Kernewek"},
	"ky": {code: "ky", name: "Kyrgyz", nativeName: "Кыргызча"},
	"la": {code: "la", name: "Latin", nativeName: "Latine"},
	"lb": {code: "lb", name: "Luxembourgish", nativeName: "Lëtzebuergesch"},
	"lg": {code: "lg", name: "Ganda", nativeName: "Luganda"},
	"li": {code: "li", name: "Limburgish", nativeName: "Limburgs"},
	"ln": {code: "ln", name: "Lingala", nativeName: "Lingála"},
	"lo": {code: "lo", name: "Lao", nativeName: "ພາສາ"},
	"lt": {code: "lt", name: "Lithuanian", nativeName: "Lietuvių kalba"},
	"lu": {code: "lu", name: "Luba-Katanga", nativeName: "Tshiluba"},
	"lv": {code: "lv", name: "Latvian", nativeName: "Latviešu valoda"},
	"mg": {code: "mg", name: "Malagasy", nativeName: "Fiteny malagasy"},
	"mh": {code: "mh", name: "Marshallese", nativeName: "Kajin M̧ajeļ"},
	"mi": {code: "mi", name: "Māori", nativeName: "Te reo Māori"},
	"mk": {code: "mk", name: "Macedonian", nativeName: "Македонски јазик"},
	"ml": {code: "ml", name: "Malayalam", nativeName: "മലയാളം"},
	"mn": {code: "mn", name: "Mongolian", nativeName: "Монгол хэл"},
	"mr": {code: "mr", name: "Marathi", nativeName: "मराठी"},
	"ms": {code: "ms", name: "Malay", nativeName: "هاس ملايو‎"},
	"mt": {code: "mt", name: "Maltese", nativeName: "Malti"},
	"my": {code: "my", name: "Burmese", nativeName: "ဗမာစာ"},
	"na": {code: "na", name: "Nauru", nativeName: "Ekakairũ Naoero"},
	"nb": {code: "nb", name: "Norwegian Bokmål", nativeName: "Norsk bokmål"},
	"nd": {code: "nd", name: "Northern Ndebele", nativeName: "IsiNdebele"},
	"ne": {code: "ne", name: "Nepali", nativeName: "नेपाली"},
	"ng": {code: "ng", name: "Ndonga", nativeName: "Owambo"},
	"nl": {code: "nl", name: "Dutch", nativeName: "Nederlands"},
	"nn": {code: "nn", name: "Norwegian Nynorsk", nativeName: "Norsk nynorsk"},
	"no": {code: "no", name: "Norwegian", nativeName: "Norsk"},
	"nr": {code: "nr", name: "Southern Ndebele", nativeName: "IsiNdebele"},
	"nv": {code: "nv", name: "Navajo", nativeName: "Diné bizaad"},
	"ny": {code: "ny", name: "Chichewa", nativeName: "ChiCheŵa"},
	"oc": {code: "oc", name: "Occitan", nativeName: "Occitan"},
	"oj": {code: "oj", name: "Ojibwe", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
	"om": {code: "om", name: "Oromo", nativeName: "Afaan Oromoo"},
	"or": {code: "or", name: "Oriya", nativeName: "ଓଡ଼ିଆ"},
	"os": {code: "os", name: "Ossetian", nativeName: "Ирон æвзаг"},
	"pa": {code: "pa", name: "Panjabi", nativeName: "ਪੰਜਾਬੀ"},
	"pi": {code: "pi", name: "Pāli", nativeName: "पाऴि"},
	"pl": {code: "pl", name: "Polish", nativeName: "Język polski"},
	"ps": {code: "ps", name: "Pashto", nativeName: "پښتو"},
	"pt": {code: "pt", name: "Portuguese", nativeName: "Português"},
	"qu": {code: "qu", name: "Quechua", nativeName: "Runa Simi"},
	"rm": {code: "rm", name: "Romansh", nativeName: "Rumantsch grischun"},
	"rn": {code: "rn", name: "Kirundi", nativeName: "Ikirundi"},
	"ro": {code: "ro", name: "Romanian", nativeName: "Română"},
	"ru": {code: "ru", name: "Russian", nativeName: "Русский"},
	"rw": {code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda"},
	"sa": {code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्"},
	"sc": {code: "sc", name: "Sardinian", nativeName: "Sardu"},
	"sd": {code: "sd", name: "Sindhi", nativeName: "सिन्धी"},
	"se": {code: "se", name: "Northern Sami", nativeName: "Davvisámegiella"},
	"sg": {code: "sg", name: "Sango", nativeName: "Yângâ tî sängö"},
	"si": {code: "si", name: "Sinhala", nativeName: "සිංහල"},
	"sk": {code: "sk", name: "Slovak", nativeName: "Slovenčina"},
	"sl": {code: "sl", name: "Slovene", nativeName: "Slovenski jezik"},
	"sm": {code: "sm", name: "Samoan", nativeName: "Gagana faa Samoa"},
	"sn": {code: "sn", name: "Shona", nativeName: "ChiShona"},
	"so": {code: "so", name: "Somali", nativeName: "Soomaaliga"},
	"sq": {code: "sq", name: "Albanian", nativeName: "Shqip"},
	"sr": {code: "sr", name: "Serbian", nativeName: "Српски језик"},
	"ss": {code: "ss", name: "Swati", nativeName: "SiSwati"},
	"st": {code: "st", name: "Southern Sotho", nativeName: "Sesotho"},
	"su": {code: "su", name: "Sundanese", nativeName: "Basa Sunda"},
	"sv": {code: "sv", name: "Swedish", nativeName: "Svenska"},
	"sw": {code: "sw", name: "Swahili", nativeName: "Kiswahili"},
	"ta": {code: "ta", name: "Tamil", nativeName: "தமிழ்"},
	"te": {code: "te", name: "Telugu", nativeName: "తెలుగు"},
	"tg": {code: "tg", name: "Tajik", nativeName: "Тоҷикӣ"},
	"th": {code: "th", name: "Thai", nativeName: "ไทย"},
	"ti": {code: "ti", name: "Tigrinya", nativeName: "ትግርኛ"},
	"tk": {code: "tk", name: "Turkmen", nativeName: "Türkmen"},
	"tl": {code: "tl", name: "Tagalog", nativeName: "Wikang Tagalog"},
	"tn": {code: "tn", name: "Tswana", nativeName: "Setswana"},
	"to": {code: "to", name: "Tonga", nativeName: "Faka Tonga"},
	"tr": {code: "tr", name: "Turkish", nativeName: "Türkçe"},
	"ts": {code: "ts", name: "Tsonga", nativeName: "Xitsonga"},
	"tt": {code: "tt", name: "Tatar", nativeName: "Татар теле"},
	"tw": {code: "tw", name: "Twi", nativeName: "Twi"},
	"ty": {code: "ty", name: "Tahitian", nativeName: "Reo Tahiti"},
	"ug": {code: "ug", name: "Uyghur", nativeName: "ئۇيغۇرچە‎"},
	"uk": {code: "uk", name: "Ukrainian", nativeName: "Українська"},
	"ur": {code: "ur", name: "Urdu", nativeName: "اردو"},
	"uz": {code: "uz", name: "Uzbek", nativeName: "Ўзбек"},
	"ve": {code: "ve", name: "Venda", nativeName: "Tshivenḓa"},
	"vi": {code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt"},
	"vo": {code: "vo", name: "Volapük", nativeName: "Volapük"},
	"wa": {code: "wa", name: "Walloon", nativeName: "Walon"},
	"wo": {code: "wo", name: "Wolof", nativeName: "Wollof"},
	"xh": {code: "xh", name: "Xhosa", nativeName: "IsiXhosa"},
	"yi": {code: "yi", name: "Yiddish", nativeName: "ייִדיש"},
	"yo": {code: "yo", name: "Yoruba", nativeName: "Yorùbá"},
	"za": {code: "za", name: "Zhuang", nativeName: "Saɯ cueŋƅ"},
	"zh": {code: "zh", name: "Chinese", nativeName: "中文"},
	"zu": {code: "zu", name: "Zulu", nativeName: "IsiZulu"},
}
